import 'normalize.css';
import '@/styles/global.scss';

import cn from 'classnames';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { Header } from '@/components/Header';

const fixel = localFont({
  src: [
    { path: '../assets/fonts/Fixel/FixelDisplay-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../assets/fonts/Fixel/FixelDisplay-Medium.woff2', weight: '500', style: 'normal' },
  ],
  variable: '--font-fixel',
});

const kyivRegion = localFont({
  src: [
    { path: '../assets/fonts/KyivRegion/KyivRegion-Regular.woff2', weight: '500', style: 'normal' },
  ],
  variable: '--font-kyiv-region',
});

export const metadata: Metadata = {
  title: 'Home | Amanogawa',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="uk">
      <body className={cn(fixel.variable, kyivRegion.variable)}>
        <Header />
        {children}
      </body>
    </html>
  );
}
